const express = require('express')
const Adminhandler= require('../controller/admin')
const Handlehome1 = require('../controller/home')
const Doctorhandler = require('../controller/doctor')
    const StudentController= require('../controller/student')
    const Suserhandler = require('../controller/suser')
  const Collegehandler = require('../controller/college')
const router = express.Router()
const studentController = new StudentController();
const suserhandler = new Suserhandler()
const handlehome1 = new Handlehome1()
const doctorhandler = new Doctorhandler()
const adminhandler = new Adminhandler()
const collegehandler = new Collegehandler()
router.get('/',handlehome1.handlehome);
router.get('/a', handlehome1.render_a);
router.post('/field',doctorhandler.selectfield)
router.get('/doctor/signup',doctorhandler.renderdocsignup)
router.get('/doctor/login',doctorhandler.renderdoctorlogin);
router.get('/student/login', studentController.renderdstudentlogin);
router.get('/student/home', studentController.getstudenthome);
router.post('/doctor/home', doctorhandler.postdoctorhome);
router.post('/student/home', studentController.poststudenthome);0
router.post('/doctor/home1',doctorhandler.postdoctorhome1)
router.post('/student/home1',studentController.poststudenthome1)
router.get('/student/appointment',studentController.getstudentappoinment)
router.get('/student/schedule',studentController.getstudentschedule)
router.get('/student/bookings',studentController.getstudentstudentbookings)
router.get('/student/settings',studentController.getstudentsettings)
router.get('/doctor/home',doctorhandler.getdoctorhome)
router.get('/doctor/schedule_sessions',doctorhandler.getdoctorschedulesessions)
router.get('/doctor/schedule',doctorhandler.getdoctorschedule)
router.get('/doctor/patients',doctorhandler.getdoctorpatients)
router.get('/doctor/settings',doctorhandler.getdoctorsettings)
router.post('/appointment', studentController.poststudentappointment);
router.post('/cancelAppointment', studentController.studentcancel);
router.post('/doctorcancel',doctorhandler.postdocotorcancel)
router.post('/acceptorreject',doctorhandler.accpectorreject)
router.post('/cancelAppointment1',studentController.studentcancel1)
router.get('/logout',doctorhandler.deletecookies)
router.post('/report',studentController.createreport)
router.get('/changepassword',studentController.redirectcp)
router.post('/confirmchangepassword',studentController.changepassword)
router.get('/aboutus',handlehome1.aboutus)
router.get('/student/forget',studentController.redirctforgetp)
router.post('/requestotp',studentController.requestotp)
router.post('/confirmchangepassword1',doctorhandler.changepassword1)
router.post('/report1',doctorhandler.createreport1)
router.get('/changepassword1',doctorhandler.redirectforget)
router.post('/verifyotp',studentController.verifyotp)
router.get('/doctor/forgetpassword',doctorhandler.redirectforgetdocotr)
router.post('/requestotpdoctor1',doctorhandler.requestotp1)
router.post('/verifyotpdoctor',doctorhandler.verifyotpdoctor)
router.post('/createmedication',doctorhandler.createprescription)
router.get('/adminlogin',adminhandler.admin_login)
router.get('/addin',adminhandler.addin)
router.post('/adminview',adminhandler.adminview)
router.post('/admindoctorview',adminhandler.admindoctorview)
router.post('/admin/patients',adminhandler.postadminpatients)
router.post('/deletepatients',adminhandler.deleteadminpatients)
router.post('/deletedoctors',adminhandler.deletedoctors)
router.get('/admin/patients',adminhandler.getadminpatients)
router.get('/adminpatients',adminhandler.adminpatients)
router.get('/admindoctor',adminhandler.admindoctor)
router.get('/addindoctor',adminhandler.addindoctor)
router.get('/adminreport',adminhandler.adminreport)
router.get('/student/signup',studentController.rendersignup)
router.get('/clearcookie',adminhandler.clearc)
router.post('/request/otp2',adminhandler.requestotp2)
router.get('/admin/forget',adminhandler.renderforgetpage)
router.post('/verifyotp2',adminhandler.verifyotp2)
router.get('/confirmchange',adminhandler.confirmc)
router.post('/changepassword2',adminhandler.changepassword2)
router.get('/admin/home',adminhandler.adminhome)
router.get('/suser/login',suserhandler.renderlogin)
router.post('/suser/home',suserhandler.checklogin)
router.get('/getmedication',studentController.getmedications)
router.get('/suser/college',suserhandler.rendercolleges)
router.get('/suser/admin',suserhandler.renderadmin)
router.get('/logoutsuser',suserhandler.logoutsuser)
router.post('/deletecollege',suserhandler.deletecolleg)
router.post('/deleteadmin',suserhandler.deleteadmin)
router.get('/addadmin',suserhandler.addadmin)
router.post('/suser/home1',suserhandler.succesfull)
router.get('/suser/home',suserhandler.rendersuserhome)
router.get('/suser/homedata',suserhandler.sendhomedata)
router.post('/requestotp123',studentController.requestotp123)
router.get('/stuednt/check',studentController.renderverfiyotp123)
router.post('/verifyotp123',studentController.verifyotp123)
router.get('/suser/forget',suserhandler.renderforget)
router.post('/requestotp4',suserhandler.requestotp)
router.post('/verifyotp4',suserhandler.verifyotp4)
router.post('/changepassword4',suserhandler.changepassword)
router.get('/getdoctorhomedetails',doctorhandler.getdoctorhomedetails)
router.get('/getadmindetails',adminhandler.getadminhomedetails)
router.get('/suserhomedetails',suserhandler.suserhomedet)
router.get('/college/signup',collegehandler.rendersignup)
router.post('/register',collegehandler.register)
router.post('/subscribe',collegehandler.subscribe)
module.exports=router
